#!/usr/bin/env python3
"""Generate original Shurale assets. Python 3; PNG rebuild needs CairoSVG.
GLBs are standard glTF 2.0, in metres, Y-up, with embedded RGBA textures.
No proprietary Meta project file is generated by this script.
"""
from pathlib import Path
import json, math, struct, hashlib
import cairosvg
ROOT=Path(__file__).resolve().parents[1]
SVG=ROOT/'graphics/svg'; PNG=ROOT/'graphics/png'; OBJ=ROOT/'spark-import/objects'
for p in (SVG,PNG,OBJ):p.mkdir(parents=True,exist_ok=True)
PAL={'ink':'#243629','fill':'#a1ac70','light':'#d7d9a0','shade':'#6c8051'}
def svgfile(name,body,w,h):
    s=f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}">{body}</svg>'
    (SVG/f'{name}.svg').write_text(s,encoding='utf8')
    cairosvg.svg2png(bytestring=s.encode(),write_to=str(PNG/f'{name}.png'))
    return s
ink=PAL['ink']; fill=PAL['fill']; light=PAL['light']; shade=PAL['shade']
atlas=f'''<g fill="{fill}" stroke="{ink}" stroke-width="10" stroke-linejoin="round" stroke-linecap="round">
<path d="M140 499 Q116 435 75 330 Q52 223 106 126 Q151 55 256 48 Q389 44 433 151 Q463 291 380 492 Z"/>
<path d="M146 449 Q207 344 175 197 M211 368 Q288 303 366 311 M155 146 Q260 107 360 159" fill="none" stroke="{shade}" stroke-width="12"/>
<path d="M615 507 C610 433 631 361 630 281 Q622 181 651 18 Q755 5 848 18 Q874 192 851 281 Q879 397 871 507 Z"/>
<path d="M650 276 Q741 235 850 272 M649 303 Q751 264 853 303" fill="none" stroke-width="6"/>
<path d="M681 60 Q661 132 668 206 M678 347 L664 445" fill="none" stroke="{light}" stroke-width="13"/>
<path d="M104 1020 Q92 906 121 812 Q108 731 134 530 Q232 517 344 530 Q359 653 351 753 Q383 875 359 1020 Z"/>
<path d="M135 781 Q243 746 350 782 M134 807 Q238 776 351 810" fill="none" stroke-width="6"/>
<path d="M169 568 Q150 637 158 706 M160 871 L156 958" fill="none" stroke="{light}" stroke-width="13"/>
<path d="M627 1020 Q610 898 635 823 Q647 668 707 572 Q736 533 768 523 Q802 535 832 594 Q871 693 866 823 Q892 914 866 1020 Z"/>
<path d="M640 856 Q750 816 865 856 M643 883 Q752 844 870 884" fill="none" stroke-width="6"/>
<path d="M712 675 Q720 596 768 549 Q815 597 823 675 Q772 704 712 675 Z" fill="{light}" stroke-width="7"/>
<path d="M675 725 Q663 782 667 804 M676 925 L670 979" fill="none" stroke="{light}" stroke-width="12"/>
</g>'''
svgfile('hand_atlas',atlas,1024,1024)
bark=f'<rect width="512" height="512" fill="{shade}"/>'
for i in range(22):
    x=i*24
    bark+=f'<path d="M{x-10} -20 Q{x+25} 100 {x-3} 227 T{x+5} 535" fill="none" stroke="{ink}" stroke-width="{3+i%3}"/>'
    bark+=f'<path d="M{x+8} 0 Q{x+25} 137 {x+12} 280 T{x+14} 512" fill="none" stroke="{fill}" stroke-width="5"/>'
svgfile('horn_bark',bark,512,512)
horn=f'<path d="M103 503 Q88 439 108 359 Q140 257 113 165 Q106 103 148 14 Q141 99 179 185 Q229 295 196 384 Q187 434 212 503 Z" fill="{fill}" stroke="{ink}" stroke-width="8"/>'
for y,x in [(450,112),(404,120),(355,140),(310,150),(263,153),(220,143),(176,126),(140,122),(95,132)]:
    horn+=f'<path d="M{x} {y} q22 -25 61 -27" stroke="{ink}" stroke-width="4" fill="none"/>'
horn+=f'<path d="M132 471 Q132 409 164 346 Q188 276 160 213 Q133 153 143 90" stroke="{light}" stroke-width="12" fill="none"/>'
svgfile('horn_profile',horn,320,512)
svgfile('icon',f'<rect width="256" height="256" rx="48" fill="{ink}"/><g transform="translate(54 16) scale(.40)">{horn}</g><path d="M35 201 Q53 161 59 131 M54 206 Q73 145 78 123 M76 210 Q91 159 99 145" stroke="{fill}" stroke-width="9" fill="none" stroke-linecap="round"/>',256,256)

class GLB:
    def __init__(self):
        self.doc={'asset':{'version':'2.0','generator':'Shurale Necrolab 0.2; original procedural assets'},'scene':0,'scenes':[{'nodes':[]}],'nodes':[],'meshes':[],'accessors':[],'bufferViews':[],'buffers':[{'byteLength':0}],'materials':[]}
        self.data=bytearray()
    def blob(self,data,target=None):
        while len(self.data)%4:self.data.append(0)
        view={'buffer':0,'byteOffset':len(self.data),'byteLength':len(data)}
        if target:view['target']=target
        idx=len(self.doc['bufferViews']);self.doc['bufferViews'].append(view);self.data.extend(data);return idx
    def accessor(self,values,typ='VEC3',component=5126):
        size={'VEC2':2,'VEC3':3,'SCALAR':1}[typ]; flat=values if size==1 else [v for row in values for v in row]
        fmt='f' if component==5126 else 'H'; v=self.blob(struct.pack('<'+fmt*len(flat),*flat),34963 if component==5123 else 34962)
        a={'bufferView':v,'byteOffset':0,'componentType':component,'count':len(values),'type':typ}
        if size>1:a.update(min=[min(x[j] for x in values) for j in range(size)],max=[max(x[j] for x in values) for j in range(size)])
        idx=len(self.doc['accessors']);self.doc['accessors'].append(a);return idx
    def material(self,name,texture=None,color=None):
        m={'name':name,'doubleSided':True,'pbrMetallicRoughness':{'metallicFactor':0,'roughnessFactor':1}}
        if texture:
            v=self.blob(Path(texture).read_bytes());ii=len(self.doc.setdefault('images',[]));self.doc['images'].append({'bufferView':v,'mimeType':'image/png'})
            ti=len(self.doc.setdefault('textures',[]));self.doc['textures'].append({'source':ii})
            m['pbrMetallicRoughness']['baseColorTexture']={'index':ti};m.update(alphaMode='MASK',alphaCutoff=.35)
            m['extensions']={'KHR_materials_unlit':{}};self.doc['extensionsUsed']=['KHR_materials_unlit']
        if color:m['pbrMetallicRoughness']['baseColorFactor']=color
        i=len(self.doc['materials']);self.doc['materials'].append(m);return i
    def mesh(self,name,verts,uv,faces,mat):
        prim={'attributes':{'POSITION':self.accessor(verts),'TEXCOORD_0':self.accessor(uv,'VEC2')},'indices':self.accessor([v for f in faces for v in f],'SCALAR',5123),'material':mat,'mode':4}
        i=len(self.doc['meshes']);self.doc['meshes'].append({'name':name,'primitives':[prim]});return i
    def node(self,name,parent=None,mesh=None,translation=None,rotation=None,scale=None):
        n={'name':name}
        if mesh is not None:n['mesh']=mesh
        if translation:n['translation']=translation
        if rotation:n['rotation']=rotation
        if scale:n['scale']=scale
        i=len(self.doc['nodes']);self.doc['nodes'].append(n)
        if parent is None:self.doc['scenes'][0]['nodes'].append(i)
        else:self.doc['nodes'][parent].setdefault('children',[]).append(i)
        return i
    def save(self,path):
        while len(self.data)%4:self.data.append(0)
        self.doc['buffers'][0]['byteLength']=len(self.data)
        j=json.dumps(self.doc,separators=(',',':')).encode();j+=b' '*((-len(j))%4)
        out=struct.pack('<4sII',b'glTF',2,12+8+len(j)+8+len(self.data))+struct.pack('<I4s',len(j),b'JSON')+j+struct.pack('<I4s',len(self.data),b'BIN\0')+self.data
        Path(path).write_bytes(out)
        return {'file':str(Path(path).relative_to(ROOT)),'bytes':len(out),'nodes':len(self.doc['nodes']),'meshes':len(self.doc['meshes']),'triangles':sum(self.doc['accessors'][p['indices']]['count']//3 for m in self.doc['meshes'] for p in m['primitives'])}

def card(g,name,w,h,cell,mat,y0=0):
    # The PNG is stored top-down. glTF v=0 refers to the image top.
    u0=(cell%2)*.5;v0=(cell//2)*.5
    return g.mesh(name,[[-w/2,y0,0],[w/2,y0,0],[w/2,y0+h,0],[-w/2,y0+h,0]],[[u0,v0+.5],[u0+.5,v0+.5],[u0+.5,v0],[u0,v0]],[(0,1,2),(0,2,3)],mat)
FINGERS=['thumb','index','middle','ring','little']
LENS=[[.045,.043,.040],[.063,.066,.061],[.074,.077,.069],[.068,.068,.061],[.055,.052,.047]]
BASES=[[-.037,-.002,.002],[-.034,.035,.002],[-.010,.043,.002],[.016,.036,.002],[.039,.018,.002]]
SPLAY=[1.04,.26,.03,-.18,-.47]
records=[]
for slot in (0,1):
    g=GLB();mat=g.material('m_hand_ink',PNG/'hand_atlas.png')
    root=g.node(f'SH_hand{slot}_calibration',scale=[1 if slot==0 else -1,1,1])
    mesh=card(g,'palm',.12,.115,0,mat,-.060);g.node(f'SH_hand{slot}_palm',root,mesh)
    for f,name in enumerate(FINGERS):
        parent=root
        for j,length in enumerate(LENS[f]):
            angle=SPLAY[f] if j==0 else .10
            mesh=card(g,f'{name}_{j}',.034 if f==0 else .032,length+0.008,[1,2,3][j],mat)
            parent=g.node(f'SH_hand{slot}_{name}_{j}',parent,mesh,BASES[f] if j==0 else [0,LENS[f][j-1],.0005],rotation=[0,0,math.sin(angle/2),math.cos(angle/2)])
    records.append(g.save(OBJ/f'hand_{slot}.glb'))
# A real 3D curved horn, not a renamed image.
g=GLB();mat=g.material('m_horn_ink',PNG/'horn_bark.png');verts=[];uv=[];faces=[]
R=18;N=16
for r in range(R+1):
    t=r/R;radius=.027*(1-t)**.85+.00035
    for k in range(N+1):
        a=2*math.pi*k/N;cx=.018*math.sin(2.8*t)-.017*t*t
        verts.append([cx+radius*math.cos(a),.275*t,.012*math.sin(math.pi*t)+radius*math.sin(a)])
        uv.append([k/N,t])
for r in range(R):
 for k in range(N):
    a=r*(N+1)+k;b=a+N+1;faces += [(a,b,a+1),(a+1,b,b+1)]
# close bottom and top using existing ring vertices; the small tip is nondegenerate.
for k in range(1,N-1):faces += [(0,k+1,k),(R*(N+1),R*(N+1)+k,R*(N+1)+k+1)]
mi=g.mesh('horn_surface',verts,uv,faces,mat);root=g.node('SH_horn_geometry',mesh=mi)
records.append(g.save(OBJ/'horn.glb'))
# A neutral ellipsoid guide to be assigned an Occluder material in Spark.
g=GLB();mat=g.material('m_head_guide',color=[.3,.4,.3,1]);vs=[];uv=[];fs=[]
for j in range(13):
 t=math.pi*j/12
 for k in range(17):
  a=2*math.pi*k/16;vs.append([.079*math.sin(t)*math.cos(a),.115*math.cos(t)+.020,.09*math.sin(t)*math.sin(a)-.035]);uv.append([k/16,j/12])
for j in range(12):
 for k in range(16):
  a=j*17+k;b=a+17
  if j>0:fs.append((a,b,a+1))
  if j<11:fs.append((a+1,b,b+1))
mi=g.mesh('head_guide',vs,uv,fs,mat);g.node('SH_head_occluder',mesh=mi)
records.append(g.save(OBJ/'head_occluder.glb'))
manifest={'version':'0.2.0','units':'metres','up_axis':'Y','fingers':FINGERS,'lengths_m':LENS,'bases_m':BASES,'splay_rad':SPLAY,'assets':records,'native_import_tested':False}
(ROOT/'graphics/ASSET_MANIFEST.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf8')
print(json.dumps(manifest,indent=2))
