from pathlib import Path
import base64,json
ROOT=Path(__file__).resolve().parents[1]
assets={k:base64.b64encode((ROOT/'spark-import/objects'/v).read_bytes()).decode() for k,v in {'h0':'hand_0.glb','h1':'hand_1.glb','horn':'horn.glb','head':'head_occluder.glb'}.items()}
html='''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Шүрәле / Некролаборатория</title>
<style>*{box-sizing:border-box}body{margin:0;background:#14271e;color:#eeeedd;font:16px system-ui,sans-serif}main{max-width:1260px;margin:0 auto;padding:34px}small{letter-spacing:.16em;color:#c3cd9d}h1{font-size:44px;line-height:1.04;margin:13px 0 16px}header p{max-width:790px;line-height:1.6;color:#bac8b5}.layout{display:grid;grid-template-columns:minmax(0,1fr) 330px;gap:25px;align-items:start}canvas{width:100%;height:auto;display:block;border-radius:12px}.plate{background:#edf0db;border-radius:12px;overflow:hidden;color:#25412e}.caption{padding:13px 18px;font-size:12px;font-weight:700;letter-spacing:.04em}aside{background:#22372b;padding:23px;border:1px solid #40523a;border-radius:12px;line-height:1.55}label{display:block;margin:18px 0 5px;font-size:14px}input{width:100%;accent-color:#bfcf86}button{border:0;border-radius:7px;padding:11px 16px;cursor:pointer;background:#d6ddb4;color:#15291d;font:600 14px system-ui;margin:7px 3px 0 0}aside p{font-size:13px;color:#c6cdbb}code{color:#d4dda5}pre{font:12px/1.4 monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:#15271c;padding:10px}select{background:#d6ddb4;color:#15291d;padding:5px 15px;font:15px system-ui}footer{font-size:12px;color:#aebaa8;line-height:1.7;margin-top:20px}@media(max-width:720px){main{padding:18px}.layout{grid-template-columns:1fr}h1{font-size:34px}}</style>
<main><header><small>НЕКРОЛАБОРАТОРИЯ / СБОРКА 0.2 / MOCK</small><h1>Шүрәле / отладка маски</h1><p>Инспектор настоящих моделей из комплекта. Движения синтетические: здесь выполняется тот же shurale.js, но модули Spark заменены нашим тестовым двойником. Камера и нейросети не используются.</p></header>
<div class="layout"><div class="plate"><canvas width="900" height="830"></canvas><div class="caption">СИНТЕТИЧЕСКАЯ ПОЗА · РЕНДЕР GLB · НЕ ЗАПУСК META SPARK</div></div><aside><strong>Отладка скрипта + ассетов</strong><label for="power">Подвижность пальцев</label><input id="power" type="range" min="0" max="1" step="0.05" value="0.8"><label for="yaw">Поворот сцены</label><input id="yaw" type="range" min="-70" max="70" value="0"><label>Лиц в тестовом входе</label><select id="faces"><option value="1">1</option><option value="0">0</option></select><label>Кистей в тестовом входе</label><select id="hands"><option value="2">2</option><option value="1">1</option><option value="0">0</option></select><br><button id="pause">Пауза</button><button id="snapshot">Кадр PNG</button><p id="clock">0.00 s</p><p>Рог: 3D. Пальцы: рисованные звенья. Управление: shurale.js.</p><p>Овал — заготовка окклюдера головы, не изображение человека.</p><pre id="debug"></pre><pre id="logs"></pre><p id="status">Загрузка встроенных ассетов…</p></aside></div><footer>Один рог · пять пальцев на кисть · три рисованных звена на палец.<br>Две кисти в этом стенде не доказывают, что выбранная версия Spark поддерживает два трекера.</footer></main>
<script>const SH_GLB=__GLB__; const SH_SPARK_SOURCE=__SPARK__;</script><script>__MOCK__</script><script>__RENDERER__</script></html>'''
html=html.replace('__MOTION__',(ROOT/'src/motion.js').read_text()).replace('__GLB__',json.dumps(assets)).replace('__SPARK__',json.dumps((ROOT/'spark-import/scripts/shurale.js').read_text())).replace('__MOCK__',(ROOT/'lab/runtime-mock.js').read_text()).replace('__RENDERER__',(ROOT/'lab/renderer.js').read_text())
(ROOT/'lab/preview.html').write_text(html,encoding='utf8')
print(ROOT/'lab/preview.html')
